/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_ruijie_classmanager_jni_SpiceHook */

#ifndef _Included_cn_com_ruijie_classmanager_jni_SpiceHook
#define _Included_cn_com_ruijie_classmanager_jni_SpiceHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_ruijie_classmanager_jni_SpiceHook
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_com_ruijie_classmanager_jni_SpiceHook_init
  (JNIEnv *, jclass);

/*
 * Class:     cn_com_ruijie_classmanager_jni_SpiceHook
 * Method:    disableMouse
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_com_ruijie_classmanager_jni_SpiceHook_disableMouse
  (JNIEnv *, jclass);

/*
 * Class:     cn_com_ruijie_classmanager_jni_SpiceHook
 * Method:    enableMouse
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_com_ruijie_classmanager_jni_SpiceHook_enableMouse
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
